### ISSUE TITLE
Compile error: invalid use of incomplete type 'struct dwarf::core::root_die'

### ISSUE THREAD

**Issue by Stefan-Schmidt** [stephenrkell/libdwarfpp#6]
I get the following when trying to compile the lib:

In file included from /usr/include/boost/type_traits/is_copy_constructible.hpp:14:0,
                 from /usr/include/boost/move/traits.hpp:21,
                 from /usr/include/boost/move/utility.hpp:21,
                 from /usr/include/boost/move/move.hpp:21,
                 from /usr/include/boost/icl/impl_config.hpp:57,
                 from /usr/include/boost/icl/interval_base_set.hpp:12,
                 from /usr/include/boost/icl/interval_set.hpp:14,
                 from /usr/include/boost/icl/interval_map.hpp:13,
                 from include/dwarfpp/spec_adt.hpp:12,
                 from src/adt.cpp:7:
/usr/include/boost/type_traits/is_base_and_derived.hpp: In instantiation of 'const bool boost::detail::is_base_and_derived_impl<boost::optional_detail::optional_tag, dwarf::core::root_die>::v
alue':
/usr/include/boost/type_traits/is_base_of.hpp:29:29:   required from 'const bool boost::detail::is_base_of_imp<boost::optional_detail::optional_tag, dwarf::core::root_die>::value'
/usr/include/boost/type_traits/is_base_of.hpp:35:52:   required from 'struct boost::is_base_of<boost::optional_detail::optional_tag, dwarf::core::root_die>'
/usr/include/boost/optional/optional.hpp:828:118:   required by substitution of 'template<class Expr> boost::optional<T>::optional(Expr&&, typename boost::disable_if_c<(boost::is_base_of<boos
t::optional_detail::optional_tag, typename boost::decay<Expr>::type>::value || boost::is_same<typename boost::decay<Expr>::type, int boost::detail::none_helper::_>::value)>::type_) [with Expr
 = dwarf::core::root_die]'
include/dwarfpp/opt.hpp:37:23:   required from 'struct dwarf::spec::optdwarf::core::root_die&'
include/dwarfpp/private/libdwarf-handles.hpp:587:69:   required from here
/usr/include/boost/type_traits/is_base_and_derived.hpp:228:51: error: invalid use of incomplete type 'struct dwarf::core::root_die'
     BOOST_STATIC_CONSTANT(bool, value = (BOOST_IS_BASE_OF(B,D) && ! ::boost::is_same<ncvB,ncvD>::value));

This is with the changes I put in #4 and #5 to get it detect libdwarf. I don't think they are related but I wanted to mention it.

Distro: Fedora 22
libdwarf version: 20150507
boost version: 1.57.0

**Comment by Stefan-Schmidt** [comment]
Still the same with latest HEAD from today.

**Comment by ratmice** [comment]
fedora 23 same thing (g++ 5.3.1), i'm not sure if its helpful,
but here is a minimal reproducer, but i'm not versed in c++ enough to understand
why the forwarding constructor to the reference somehow requires complete type info

```
#include <boost/optional.hpp>

using boost::optional;

template<typename T, typename Enabler = void>
struct opt : optional<T>
{
  typedef optional<T> super;
  using optional<T>::optional;
};

struct foo;
struct bar {};
struct baz {
  // works..
  inline foo & opt_something(boost::optional<foo&> arg) { return *arg; }
  inline bar & opt_something(opt<bar&> arg) { return *arg; }
  // complains about foward decl of foo;
#ifndef NO_COMPILE_ERROR
  inline foo & opt_something(opt<foo&> arg) { return *arg; }
#endif
};


int main() {
  return 0;
}
```

**Comment by stephenrkell** [comment]
Thanks for the reproducer. The solution is probably to avoid the forward declaration. 

The source file that Stefan reported the problem in (adt.cpp) is now removed. Can one of you please give me a full compiler output from the failing build on current master?

**Comment by ratmice** [comment]
here is all the output from the failing compile, if it is something specific to our version of boost, rather than the compiler, let me know if pre-processed sources would help at all.

In file included from /usr/include/boost/config.hpp:61:0,
                 from /usr/include/boost/optional/optional.hpp:24,
                 from /usr/include/boost/optional.hpp:15,
                 from include/dwarfpp/lib.hpp:20,
                 from src/expr.cpp:13:
/usr/include/boost/type_traits/is_base_and_derived.hpp: In instantiation of ‘const bool boost::detail::is_base_and_derived_impl<boost::optional_detail::optional_tag, dwarf::core::root_die>::value’:
/usr/include/boost/type_traits/is_base_of.hpp:29:11:   required from ‘const bool boost::detail::is_base_of_imp<boost::optional_detail::optional_tag, dwarf::core::root_die>::value’
/usr/include/boost/type_traits/is_base_of.hpp:35:1:   required from ‘struct boost::is_base_of<boost::optional_detail::optional_tag, dwarf::core::root_die>’
/usr/include/boost/optional/optional.hpp:841:132:   required by substitution of ‘template<class Expr> boost::optional<T>::optional(Expr&&, typename boost::disable_if_c<(boost::is_base_of<boost::optional_detail::optional_tag, typename boost::decay<Expr>::type>::value || boost::is_same<typename boost::decay<Expr>::type, boost::none_t>::value)>::type*) [with Expr = dwarf::core::root_die]’
include/dwarfpp/opt.hpp:37:23:   required from ‘struct dwarf::spec::optdwarf::core::root_die&’
include/dwarfpp/private/libdwarf-handles.hpp:587:69:   required from here
/usr/include/boost/type_traits/is_base_and_derived.hpp:228:42: error: invalid use of incomplete type ‘struct dwarf::core::root_die’
     BOOST_STATIC_CONSTANT(bool, value = (BOOST_IS_BASE_OF(B,D) && ! ::boost::is
                                          ^
In file included from include/dwarfpp/lib.hpp:31:0,
                 from src/expr.cpp:13:
include/dwarfpp/attr.hpp:38:10: note: forward declaration of ‘struct dwarf::core::root_die’
   struct root_die;
          ^

**Comment by stephenrkell** [comment]
Thanks for this. I still can't reproduce... tried boost 1.55 and 1.58, and g++ 4.9.2 and 5.2.1. At this point, preprocessed source would be very helpful -- thanks in advance. (I don't have gcc 5.3.x easily available here, though will try to fix that.)

**Comment by stephenrkell** [comment]
Scratch that -- rebuilding full libdwarfpp reveals the problem. Fix pending....

**Comment by ratmice** [comment]
Confirming that your changes fixed this issue here
