### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by nivpgir** [stephenrkell/libdwarfpp#9]
I followed the build instructions for this, and ended up with the following compilation error:
```
src/dies.cpp: In member function ‘virtual dwarf::spec::opt<dwarf::core::type_scc_t> dwarf::core::type_die::get_scc() const’:
src/dies.cpp:2560:62: error: no matching function for call to ‘dwarf::spec::opt<std::shared_ptr<dwarf::core::type_scc_t> >::opt(std::shared_ptr<dwarf::core::type_scc_t>)’
       = opt<shared_ptr<type_scc_t> >(shared_ptr<type_scc_t>());
```

this happens when I run make, all other build stages seem to run fine.
I would appreciate some assistance with solving this.

on arch linux ,all packages at latest, 
gcc: 8.1.1 20180531
boost: 1.67.0-5

any more relevant detail will gladly be supplied if needed.

**Comment by nivpgir** [comment]
a bit tracing led me to: `include/dwarfpp/opt.hpp` where I realized the issue lies somehow with the specialized definition of `opt<shared_ptr<T> >` . my templates skills are pretty rusty but it seems that for some reason it doesn't find a definition for the constructor for `opt<shared_ptr<T> >` ?

just to confirm that that's where the problem lies I commented out the specialized part for  `opt<shared_ptr<T> >` and with that (and some tweaking to library search paths that ac  doesn't seems to resolve, but this is a subject for a different issue), the build finished successfully.

I don't have any guesses for why that specialized case is there, or why it's compilation fails only for me, so I'll appreciate your response regarding this.

**Comment by nivpgir** [comment]
#8 
found that this PR fixes the issue.

**Comment by stephenrkell** [comment]
Great that you got it building. Yes, I've been bitten by this before. Different compilers/versions have slightly different readings of the rules for template instantiation and how it interacts with overloading. 

Instead of commenting out the extra case, you could try tweaking the problematic use sites so that it more explicitly invokes the right template instance, e.g. by using a cast or an explicit constructor call.

I'll take a closer look shortly (just starting a new job today so I'm all over the place). I've just commented on #8 because it is not quite right at the moment.

**Comment by stephenrkell** [comment]
Now fixed.
